FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:prod

FROM nginxinc/nginx-unprivileged:alpine
COPY nginx.funtime.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/monorepo/browser /usr/share/nginx/html
EXPOSE 8080
